Add  `Ctrl + Z `shortcut to the input.
makepad/makepad pull request #613
Opened 2024-12-13 03:01 UTC by Guocork

After some investigation, I found that on many platforms, the shortcuts for undo and redo are `Ctrl + Z` and `Ctrl + Shift + Z`. So far, I haven’t seen any platform (I tested on Windows, Linux, and Web) that supports` Logo + Z` or `Logo + Shift + Z`. Should we still keep the `Logo + Z` shortcut? Also, I noticed that on some apps or platforms (especially on the Web), `Ctrl + Y` is used for redo. Should Makepad also support the `Ctrl + Y` shortcut?

2024-12-16 21:23 UTC, kevinaboos commented
for this, you can use my new addition of the `is_primary()` function to the `KeyModifier` struct, which will correctly return whether `Ctrl` is pressed on Windows/Linux or `Logo` is pressed on macOS.

2024-12-16 21:24 UTC, kevinaboos commented
https://github.com/makepad/makepad/pull/590

2024-12-17 02:35 UTC, Guocork commented
> for this, you can use my new addition of the `is_primary()` function to the `KeyModifier` struct, which will correctly return whether `Ctrl` is pressed on Windows/Linux or `Logo` is pressed on macOS.
> 
> See the PR here: #590

Ok, thank you.I looked into it and found that the undo shortcut is `Command+Z`/ `Logo + Z `on macOS(cmd = logo in Mac), while `Ctrl+Z` is more common on non-macOS platforms, which better aligns with user habits.

2024-12-19 02:37 UTC, kevinaboos requested changes
Currently, this code activates an Undo operation if either <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Z</kbd>  or <kbd>Logo</kbd> + <kbd>Shift</kbd> + <kbd>Z</kbd> is pressed. IMO, this is incorrect as the former is unexpected behavior on macOS, while the latter is unexpected on Linux/Windows.

Instead, this should activate an Undo operation only if  `KeyModifiers::is_primary()` is true and <kbd>Shift</kbd> + <kbd>Z</kbd> are pressed.

2024-12-20 10:14 UTC, Guocork commented
> Currently, this code activates an Undo operation if either Ctrl + Shift + Z or Logo + Shift + Z is pressed. IMO, this is incorrect as the former is unexpected behavior on macOS, while the latter is unexpected on Linux/Windows.
> 
> Instead, this should activate an Undo operation only if `KeyModifiers::is_primary()` is true and Shift + Z are pressed.

Ok, I got it and fix it, Thank you.

2024-12-20 19:29 UTC, kevinaboos approved these changes
LGTM

2025-01-04 08:45 UTC, merged